apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/managed-by: dinghy.dev
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: dinghy.dev
  name: my-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9376
  selector:
    app.kubernetes.io/name: MyApp
