apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
patches:
- path: patches/00.yaml
  target: { kind: Service, version: v1, name: my-service }
- path: patches/01.yaml
  target: { kind: Service, version: v1, name: my-service }
