apiVersion: dinghy.dev/v1alpha1
kind: Config
resources:
- deployment.yaml
mutate:
- uses: builtin.dinghy.dev/strategicMergePatch
  with:
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: nginx
      template:
        metadata:
          labels:
            app.kubernetes.io/name: nginx
