apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- https://github.com/johnhoman/nop.git/1
mutate:
- uses: builtin.kustomize.k8s.io/prependNamePrefix
  with:
    namePrefix: bar-
  selector: {}
