apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: foo
  labels:
    app.kubernetes.io/name: nginx
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app.kubernetes.io/name: nginx

