# patch was doing something to the spec that
# made the merge patch on merge on port name
apiVersion: dinghy.dev/v1alpha1
kind: Config
resources:
- service.yaml
mutate:
- uses: builtin.dinghy.dev/strategicMergePatch
  with:
    spec:
      type: ClusterIP
      ports:
      - port: 80
        targetPort: 9000
- uses: builtin.dinghy.dev/strategicMergePatch
  with:
    spec:
      type: NodePort
      ports:
      - port: 80
        name: http-app