apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- component
mutate:
- uses: builtin.kustomize.k8s.io/name
  with:
    prefix: foo-
    suffix: -bar
- uses: builtin.kustomize.k8s.io/namespace
  with:
    replace: foobar
- uses: builtin.kustomize.k8s.io/patch
  selector:
    kinds:
    - ConfigMap
  with:
    # I need to return this value to the given transform context,
    # so just get the value from the field path, then pass it in
    # to
    fieldPath: data.BAR
    value: poo
