apiVersion: dinghy.dev/v1alpha1
kind: Config
resources:
- service.yaml
mutate:
- uses: builtin.dinghy.dev/matchLabels
  with:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: testing.dinghy.dev
