apiVersion: dinghy.dev/v1alpha1
kind: Config
resources:
- deployment.yaml
mutate:
- uses: builtin.dinghy.dev/jsonpatch
  with:
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: nginx
    - op: add
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: nginx
