apiVersion: dinghy.dev/v1alpha1
kind: Config
resources:
- deployment.yaml
mutate:
- uses: builtin.dinghy.dev/patch
  with:
    fieldPaths:
    - spec.replicas
    value: 10
- uses: builtin.dinghy.dev/patch
  with:
    fieldPaths:
    - spec.template.metadata.labels
    - spec.selector.matchLabels
    value:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/part-of: testing.dinghy.dev
- uses: builtin.dinghy.dev/patch
  with:
    fieldPaths:
    - metadata.labels['app.kubernetes.io/managed-by']
    value: dinghy.dev
