apiVersion: v1
data:
  PORT: "9876"
kind: ConfigMap
metadata:
  name: my-service
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9376
  selector:
    app.kubernetes.io/name: MyApp
