apiVersion: dinghy.dev/v1alpha1
kind: Config
resources:
- deployment.yaml
mutate:
- uses: builtin.dinghy.dev/metadata/annotations
  with:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: testing.dinghy.dev
- uses: builtin.dinghy.dev/script/js
  with:
    script: |
      function mutate(o, c) {
        if (o.metadata.annotations === undefined) {
          o.metadata.annotations = {}
        }
        o.metadata.annotations["dinghy.dev/script"] = `Hello, ${c.params.name}!`
      }
    config:
      params:
        name: World
